
package io.vksn.summons.summonsservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SummonsService", targetNamespace = "http://vksn.io/summons/summonsService/", wsdlLocation = "META-INF/wsdl/summons-service.wsdl")
public class SummonsService
    extends Service
{

    private final static URL SUMMONSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUMMONSSERVICE_EXCEPTION;
    private final static QName SUMMONSSERVICE_QNAME = new QName("http://vksn.io/summons/summonsService/", "SummonsService");

    static {
        SUMMONSSERVICE_WSDL_LOCATION = io.vksn.summons.summonsservice.SummonsService.class.getClassLoader().getResource("META-INF/wsdl/summons-service.wsdl");
        WebServiceException e = null;
        if (SUMMONSSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'META-INF/wsdl/summons-service.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SUMMONSSERVICE_EXCEPTION = e;
    }

    public SummonsService() {
        super(__getWsdlLocation(), SUMMONSSERVICE_QNAME);
    }

    public SummonsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUMMONSSERVICE_QNAME, features);
    }

    public SummonsService(URL wsdlLocation) {
        super(wsdlLocation, SUMMONSSERVICE_QNAME);
    }

    public SummonsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUMMONSSERVICE_QNAME, features);
    }

    public SummonsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SummonsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SummonsServiceWS
     */
    @WebEndpoint(name = "SummonsService")
    public SummonsServiceWS getSummonsService() {
        return super.getPort(new QName("http://vksn.io/summons/summonsService/", "SummonsService"), SummonsServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SummonsServiceWS
     */
    @WebEndpoint(name = "SummonsService")
    public SummonsServiceWS getSummonsService(WebServiceFeature... features) {
        return super.getPort(new QName("http://vksn.io/summons/summonsService/", "SummonsService"), SummonsServiceWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUMMONSSERVICE_EXCEPTION!= null) {
            throw SUMMONSSERVICE_EXCEPTION;
        }
        return SUMMONSSERVICE_WSDL_LOCATION;
    }

}
